{% set version = "0.16.3" %}
{% set tf_version = "1.13.1" %}

package:
  name: horovod
  version: {{ version }}

source:
  git_url: https://github.com/horovod/horovod.git
  git_rev: v{{ version}}

build:
  number: 0
  skip: True  # [not x86_64]
  string: {{ horovod_variant }}_py{{ py_version | replace(".", "") }}h{{PKG_HASH}}_{{ PKG_BUILDNUM }}  # [linux or win-64]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # conda build requirements
    - python {{ py_version }}
    # requirements specified by the package itself
    - cloudpickle
    - psutil
    - six
    - tensorflow-gpu =={{tf_version}}
    - pytorch >=0.4.0
    - flatbuffers >=1.11.0  # requried for both tensorflow and pytorch plugins
    - openmpi ==3.1.2  # 3.1.3 does not work
    - cffi >=1.4.0  # required if pytorch support is enabled
    - protobuf ==3.6.1
    - cudatoolkit {{ cudatoolkit }}*
  run:
    - python {{ py_version }}                     # [linux or win-64]
    - _horovod_select =={{ select_version }}        # [linux or win-64]
    - cloudpickle
    - psutil
    - six
    - tensorflow-gpu =={{tf_version}}
    - pytorch >=0.4.0
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}
    - cffi >=1.4.0  # required if pytorch support is enabled

test:
  imports:
    - horovod
  commands:
    - horovodrun --help

about:
  home: https://github.com/horovod/horovod
  license: Apache 2.0
  license_family: APACHE
  summary: |
    Horovod is a distributed training framework for TensorFlow, Keras,
    PyTorch, and MXNet.
  description: |
    Horovod is a distributed training framework for TensorFlow, Keras,
    PyTorch, and MXNet. The goal of Horovod is to make distributed Deep
    Learning fast and easy to use.
  dev_url: https://github.com/horovod/horovod
  doc_url: https://github.com/horovod/horovod/blob/master/README.md
  doc_source_url: https://github.com/horovod/horovod/tree/master/docs
